config/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import RedirectView, TemplateView
from qr_code import urls as qr_code_urls

from todovoodoo.core.views import public_station_view

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="core:lists-view")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("todovoodoo.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("app/", include("todovoodoo.core.urls", namespace="core")),
    path("api/v1/", include("todovoodoo.api.urls", namespace="todovoodoo.api")),
    path("qr_code/", include(qr_code_urls, namespace="qr_code")),
    path("s/<slug:slug>/", view=public_station_view, name="stations-public-view"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [path("django-rq/", include("django_rq.urls"))]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path("400/", default_views.bad_request, kwargs={"exception": Exception("Bad Request!")}),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/", default_views.page_not_found, kwargs={"exception": Exception("Page not Found")}
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

todovoodoo/api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework_swagger.views import get_swagger_view

from .viewsets import TodoListViewSet, ListItemViewSet

app_name = "api"

schema_view = get_swagger_view(title="Todovoodoo API")

router = routers.DefaultRouter(trailing_slash=True)
router.register(r"lists", ListItemViewSet, basename="TodoList")
router.register(r"items", TodoListViewSet, basename="ListItem")

urlpatterns = [
    path("", schema_view),
    path("rest-auth/", include("rest_auth.urls")),
    path("rest-auth/registration/", include("rest_auth.registration.urls")),
] + router.urls

todovoodoo/core/urls.py
from django.urls import path, include


from todovoodoo.core.views import (
    master_list_view,
    station_view,
    public_station_view,
    station_tag_view,
    list_item_delete_view,
    list_item_update_view,
    list_item_create_view,
    todo_list_create_view,
    todo_list_update_view,
    station_delete_view,
)

app_name = "core"
urlpatterns = [
    path("", view=master_list_view, name="master-list"),
    path("stations", view=station_view, name="lists-view"),
    path("stations/tags/", view=station_tag_view, name="tags-view"),
    path("stations/<uuid:pub_id>/", view=station_view, name="lists-view"),
    path("stations/create/", view=todo_list_create_view, name="create-todo-list"),
    path("stations/update/<uuid:pub_id>/", view=todo_list_update_view, name="update-todo-list"),
    path("stations/delete/<uuid:pub_id>/", view=station_delete_view, name="delete-station"),
    path("items/create/<uuid:pub_id>/", view=list_item_create_view, name="create-item"),
    path("items/update/<uuid:pub_id>/", view=list_item_update_view, name="update-item"),
    path("items/delete/<uuid:pub_id>/", view=list_item_delete_view, name="delete-item"),
    path("public/stations/", view=public_station_view, name="stations-public-view"),
    path("public/stations/<slug:slug>/", view=public_station_view, name="stations-public-view"),
]

todovoodoo/users/urls.py
from django.urls import path

from todovoodoo.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

todovoodoo/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CASCADE, CharField, OneToOneField, TextField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from fernet_fields import EncryptedCharField
from model_utils.models import TimeStampedModel


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    pushover_user_key = EncryptedCharField(
        _("Pushover User Key"), null=True, default=None, blank=True, max_length=255
    )
    pushover_api_token = EncryptedCharField(
        _("Pushover API Token"), null=True, default=None, blank=True, max_length=255
    )

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

todovoodoo/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.forms import CharField
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

todovoodoo/core/views/create.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import IntegrityError
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.utils.timezone import localdate, now
from django.views.generic import CreateView, DeleteView, TemplateView, UpdateView

from todovoodoo.core.forms import (
    ListItemForm,
    ReportEntryForm,
    StationForm,
    StationItemForm,
    TodoListForm,
)
from todovoodoo.core.models import ListItem, ReportEntry, Station, StationItem, TodoList
from todovoodoo.core.tasks import send_pushover_notification


class ReportEntryCreateView(CreateView):

    slug_url_kwarg = "slug"
    slug_field = "slug"
    form_class = ReportEntryForm
    model = ReportEntry

    def get_context_data(self, *args, **kwargs):
        """Use this to add extra context."""
        context = super().get_context_data(**kwargs)
        context["hide_nav"] = True

        slug = self.kwargs.get("slug")
        if not slug:
            return context

        try:
            station = Station.objects.get(slug=slug)
        except Station.DoesNotExist:
            messages.add_message(self.request, messages.ERROR, "Error finding station.")
            return context
        else:
            context.update({"slug": slug, "station": station})

        return context

    def get_success_url(self):
        return reverse("core:stations-public-view")

    def form_valid(self, form):
        slug = self.kwargs["slug"]
        try:
            station = Station.objects.get(slug=slug)
        except Station.DoesNotExist:
            return redirect(reverse("core:stations-public-view", args=[slug]))
        form.instance.station = station
        form.instance.set_report_type()
        entry = form.save()
        send_pushover_notification.delay(
            entry=entry, photo_url=self.request.build_absolute_uri(entry.photo_upload.url)
        )
        return super().form_valid(form)


public_station_view = ReportEntryCreateView.as_view()


class StationView(LoginRequiredMixin, TemplateView):

    template_name = "core/station_configuration.html"

    def get_context_data(self, pub_id=None, **kwargs):
        """Use this to add extra context."""
        todo_lookup_args = {"pub_id": pub_id} if pub_id is not None else {}
        station = Station.objects.filter(owner=self.request.user, **todo_lookup_args).first()
        context = super(StationView, self).get_context_data(**kwargs)

        if not station:
            return {"stations": [], "todo_list_form": StationForm()}

        context.update(
            {
                "stations": Station.objects.filter(owner=self.request.user).order_by("created"),
                "list_items": station.stationitem_set.order_by("-created"),
                "active_list": station,
                "can_delete": True if station.name != "main" else False,
                "list_item_edit_form": ListItemForm(prefix="list_item_edit"),
                "station_item_create_form": StationItemForm(),
                "todo_list_form": StationForm(),
                "station_url": self.request.build_absolute_uri(
                    reverse("core:lists-view", args=[station.pub_id])
                ),
            }
        )
        return context


station_view = StationView.as_view()


class ListItemCreate(LoginRequiredMixin, CreateView):

    form_class = ListItemForm
    prefix = "list_item_create"
    model = ListItem

    def form_valid(self, form):
        try:
            todo_list = TodoList.objects.get(owner=self.request.user, pub_id=self.kwargs["pub_id"])
        except TodoList.DoesNotExist:
            return redirect(reverse("core:lists-view"))
        form.instance.todo_list = todo_list
        form.instance.due_date = localdate(now())
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return self.request.POST.get("next", self.success_url)


list_item_create_view = ListItemCreate.as_view()


class ListItemDelete(LoginRequiredMixin, DeleteView):

    slug_url_kwarg = "pub_id"
    slug_field = "pub_id"
    success_url = reverse_lazy("core:lists-view")

    def get_queryset(self):
        return ListItem.objects.filter(todo_list__owner=self.request.user)

    def get_success_url(self):
        return self.request.POST.get("next", self.success_url)


list_item_delete_view = ListItemDelete.as_view()


class ListItemUpdate(LoginRequiredMixin, UpdateView):

    slug_url_kwarg = "pub_id"
    slug_field = "pub_id"
    prefix = "list_item_edit"
    success_url = reverse_lazy("core:lists-view")
    fields = ["description", "always_show"]

    def get_queryset(self):
        return ListItem.objects.filter(todo_list__owner=self.request.user)

    def get_success_url(self):
        return self.request.POST.get("next", self.success_url)


list_item_update_view = ListItemUpdate.as_view()


class StationCreate(LoginRequiredMixin, CreateView):
    """ Creates a new list for items. """

    form_class = StationForm
    model = Station
    success_url = reverse_lazy("core:lists-view")
    template_name = "core/station_configuration.html"

    def post(self, request, *args, **kwargs):
        try:
            return super().post(request, *args, **kwargs)
        except IntegrityError:
            messages.add_message(
                request, messages.ERROR, "All of your Station names must be unique."
            )
            return redirect(request.POST.get("next", self.success_url))

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.add_message(self.request, messages.ERROR, form.errors)
        return redirect(self.request.POST.get("next", self.success_url))

    def get_success_url(self):
        return self.request.POST.get("next", self.success_url)


todo_list_create_view = StationCreate.as_view()


class TodoListUpdate(LoginRequiredMixin, UpdateView):

    slug_url_kwarg = "pub_id"
    slug_field = "pub_id"
    form_class = TodoListForm
    success_url = reverse_lazy("core:lists-view")

    def get_queryset(self):
        return TodoList.objects.filter(owner=self.request.user)

    def get_success_url(self):
        return self.request.POST.get("next", self.success_url)


todo_list_update_view = TodoListUpdate.as_view()


class StationDelete(LoginRequiredMixin, DeleteView):
    """ Deletes a station. """

    slug_url_kwarg = "pub_id"
    slug_field = "pub_id"
    success_url = reverse_lazy("core:lists-view")

    def get_queryset(self):
        return Station.objects.filter(owner=self.request.user)


station_delete_view = StationDelete.as_view()

todovoodoo/core/views/master.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.timezone import now, localdate
from django.views import View
from django.views.generic import ListView

from todovoodoo.core.models import Station, ListItem, ReportEntry


class UserReportView(LoginRequiredMixin, ListView):
    """ Master view that includes all stations QR codes. """

    model = ReportEntry
    template_name = "core/user_reports.html"
    context_object_name = "reports"
    paginate_by = 10

    def get_queryset(self):
        return ReportEntry.objects.filter(station__owner=self.request.user).order_by("created")


master_list_view = UserReportView.as_view()


class TagView(LoginRequiredMixin, ListView):
    """ Master view that includes all stations QR codes. """

    model = Station
    template_name = "core/station_tags.html"
    context_object_name = "stations"
    paginate_by = 10

    def get_queryset(self):
        return Station.objects.filter(Q(owner=self.request.user))


station_tag_view = TagView.as_view()


class ListItemPostpone(LoginRequiredMixin, View):
    """ Handle postponing items to another date. """

    def post(self, request, *args, **kwargs):
        redirect_url = request.POST.get("next", reverse("core:master-list"))
        try:
            list_item = ListItem.objects.get(pub_id=self.kwargs["pub_id"])
            if list_item.always_show:
                messages.add_message(
                    request, messages.WARNING, "Item marked to always show in master."
                )
            else:
                list_item.postpone(int(request.POST.get("days", 0)))
        except (ListItem.DoesNotExist, ValueError):
            messages.add_message(request, messages.ERROR, "Couldn't postpone item.")
        else:
            messages.add_message(
                request, messages.WARNING, f"Postponed until {list_item.due_date.isoformat()}."
            )

        return redirect(redirect_url)


postpone_item_view = ListItemPostpone.as_view()


class ListItemComplete(LoginRequiredMixin, View):
    """ Handle postponing items to another date. """

    def post(self, request, *args, **kwargs):
        redirect_url = request.POST.get("next", reverse("core:master-list"))
        try:
            list_item = ListItem.objects.get(pub_id=self.kwargs["pub_id"])
            list_item.mark_complete()
            if list_item.always_show:
                messages.add_message(
                    request,
                    messages.INFO,
                    'Marking an item as complete will clear "Always show in master" property.',
                )
        except (ListItem.DoesNotExist, ValueError):
            messages.add_message(request, messages.ERROR, "Couldn't mark item complete.")
        else:
            messages.add_message(
                request, messages.INFO, f"Completed until {list_item.due_date.isoformat()}."
            )

        return redirect(redirect_url)


complete_item_view = ListItemComplete.as_view()

todovoodoo/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name", "pushover_user_key", "pushover_api_token"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

todovoodoo/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

todovoodoo/templates/base.html
{% load tz %}
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}todovoodoo{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicons/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicons/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicons/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'images/favicons/site.webmanifest' %}">

  {% block css %}


  <!-- Your stuff: Third-party CSS libraries go here -->

  <!-- This file stores project-specific CSS -->

  <link href="{% static 'css/project.min.css' %}" rel="stylesheet">


  {% endblock %}

</head>

<body>

  <div class="m-b-1">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand"
        href="{% if not hide_nav %}{% url 'core:master-list' %}{% else %}#{% endif %}">todovoodoo</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if not hide_nav %}
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:lists-view' %}">{% trans "Add/Edit Station Configuration" %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:master-list' %}">{% trans "View User Reports" %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:tags-view' %}">{% trans "QR Code Tags" %}</a>
          </li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
          </li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
          </li>
          {% else %}
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
          </li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
          </li>
          {% endif %}
          {% endif %}
        </ul>
      </div>
    </nav>

  </div>

  <div class="container">

    {% if messages %}
    {% for message in messages %}
    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
    {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock content %}

  </div> <!-- /container -->

  {% block modal %}{% endblock modal %}

  <!-- Le javascript
    ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  {% block javascript %}

  <!-- Vendor dependencies bundled as one file-->

  <script src="{% static 'js/vendors.js' %}"></script>



  <!-- place project specific Javascript in this file -->

  <script src="{% static 'js/project.js' %}"></script>


  {% endblock javascript %}
</body>

</html>